In [36]:
from __future__ import print_function
import numpy as np
np.random.seed(1337)  # for reproducibility

from keras.datasets import mnist
from keras.layers import Input, Dense, Activation, Dropout, Conv1D, Conv2D, GlobalMaxPooling1D, Embedding, GlobalMaxPooling2D, MaxPooling2D, Flatten

from keras.models import Model, Sequential
from keras.utils import np_utils

In [2]:
batch_size = 128
nb_classes = 10
nb_epoch = 20

In [68]:
# the data, shuffled and split between train and test sets
(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train.reshape(60000, 784)
X_test = X_test.reshape(10000, 784)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

print(X_train.shape)
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

(60000, 784)
60000 train samples
10000 test samples


In [4]:
# convert class vectors to binary class matrices
Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)

n_hidden_layers = 2
inputs = Input(shape=(784,))
x = inputs

for i in range(0, n_hidden_layers):
    x = Dense(units=64, activation='relu')(x)

x = Dropout(0.5, noise_shape=None, seed=None)(x)
predictions = Dense(nb_classes, activation='softmax')(x)
# convert class vectors to binary class matrices

model = Model(input=inputs, output=predictions)

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:16: UserWarning: Update your `Model` call to the Keras 2 API: `Model(outputs=Tensor("de..., inputs=Tensor("in...)`
  app.launch_new_instance()


In [5]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 784)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_2 (Dense)              (None, 64)                4160      
_________________________________________________________________
dropout_1 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 10)                650       
Total params: 55,050
Trainable params: 55,050
Non-trainable params: 0
_________________________________________________________________


In [6]:
history = model.fit(X_train, Y_train,
                    batch_size=batch_size, nb_epoch=nb_epoch,
                    verbose=1, validation_data=(X_test, Y_test))
score = model.evaluate(X_test, Y_test, verbose=0)

print('Test score:', score)
print('Test accuracy:', score)

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:3: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  This is separate from the ipykernel package so we can avoid doing imports until


Train on 60000 samples, validate on 10000 samples
Epoch 1/20
60000/60000 [==============================] - 3s 58us/step - loss: 0.6040 - acc: 0.8207 - val_loss: 0.2225 - val_acc: 0.9335
Epoch 2/20
60000/60000 [==============================] - 4s 62us/step - loss: 0.2750 - acc: 0.9234 - val_loss: 0.1629 - val_acc: 0.9515
Epoch 3/20
14592/60000 [======>.......................] - ETA: 3s - loss: 0.2177 - acc: 0.9427

KeyboardInterrupt: 

In [5]:
# the data, shuffled and split between train and test sets
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train = X_train.reshape(60000, 28, 28, 1) 
X_test = X_test.reshape(10000, 28, 28, 1)
#X_train_new = [X_train, zero1.T]
#X_test_new = np.r_[X_test, zero2.T]
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

print(X_train.shape)
print(X_train)
print(X_test.shape)
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)

(60000, 28, 28, 1)
[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0

In [60]:
inputs = Input(shape=(28, 28, 1, ))

x = inputs

predictions = Conv2D(filters = 32, kernel_size = 5,padding='Same', activation='relu')(x)
predictions = GlobalMaxPooling2D()(predictions)
predictions = Dense(units = 256, activation ='relu')(predictions)
predictions = Dropout(0.25)(predictions)
predictions = Dense(nb_classes, activation='softmax')(predictions)
#model = Sequential()
#model.add(Conv2D(filters= 32, kernel_size=(5,5), padding='Same', activation='relu',input_shape=(28,28,1,)))
#model.add(MaxPool2D(pool_size=(2,2)))
#model.add(Flatten())
#model.add(Dense(256, activation='relu'))    
#model.add(Dropout(0.25))
#model.add(Dense(10, activation='softmax'))  

model_conv = Model(input=inputs, output=predictions)

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:19: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("in..., outputs=Tensor("de...)`


In [61]:
model_conv.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model_conv.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_33 (InputLayer)        (None, 28, 28, 1)         0         
_________________________________________________________________
conv2d_45 (Conv2D)           (None, 28, 28, 32)        832       
_________________________________________________________________
global_max_pooling2d_8 (Glob (None, 32)                0         
_________________________________________________________________
dense_25 (Dense)             (None, 256)               8448      
_________________________________________________________________
dropout_13 (Dropout)         (None, 256)               0         
_________________________________________________________________
dense_26 (Dense)             (None, 10)                2570      
Total params: 11,850
Trainable params: 11,850
Non-trainable params: 0
_________________________________________________________________


In [62]:
history = model_conv.fit(X_train, Y_train,
                    batch_size=batch_size, nb_epoch=nb_epoch,
                    verbose=1, validation_data=(X_test, Y_test))
score = model_conv.evaluate(X_test, Y_test, verbose=0)

print('Test score:', score)
print('Test accuracy:', score)

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:3: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  This is separate from the ipykernel package so we can avoid doing imports until


Train on 60000 samples, validate on 10000 samples
Epoch 1/20
60000/60000 [==============================] - 329s 5ms/step - loss: 1.3064 - acc: 0.5724 - val_loss: 0.6496 - val_acc: 0.8116
Epoch 2/20
60000/60000 [==============================] - 325s 5ms/step - loss: 0.5860 - acc: 0.8139 - val_loss: 0.4347 - val_acc: 0.8642
Epoch 3/20
60000/60000 [==============================] - 339s 6ms/step - loss: 0.4344 - acc: 0.8610 - val_loss: 0.3720 - val_acc: 0.8802
Epoch 4/20
60000/60000 [==============================] - 332s 6ms/step - loss: 0.3698 - acc: 0.8818 - val_loss: 0.2823 - val_acc: 0.9136
Epoch 5/20
60000/60000 [==============================] - 329s 5ms/step - loss: 0.3318 - acc: 0.8940 - val_loss: 0.2577 - val_acc: 0.9200
Epoch 6/20
60000/60000 [==============================] - 325s 5ms/step - loss: 0.3040 - acc: 0.9035 - val_loss: 0.2435 - val_acc: 0.9232
Epoch 7/20
60000/60000 [==============================] - 323s 5ms/step - loss: 0.2856 - acc: 0.9088 - val_loss: 0.2362 - 